apiVersion: apps/v1
kind: Deployment
metadata:
  name: suridevops-deploy
  labels:
    app: suridevops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: suridevops-app
  template:
    metadata:
      labels:
        app: suridevops-app
    spec:
      containers:
      - name: suridevops-mvn-container
        image: suridevops/suridevops-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: suridevops-np-service
  labels:
    app: suridevops-app
spec:
  selector:
    app: suridevops-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
